replicaCount: 1
image:
  repository: pavanym6/go-web-app
  pullPolicy: IfNotPresent
  tag: "21904693989"

ingress:
  enabled: true
  className: "nginx"
  annotations:
    kubernetes.io/ingress.class: nginx
  hosts:
    - host: go-web-app.54.196.237.206.nip.io
      path:
        - path: /
          pathType: Prefix

